// Generated by tools/Import-PresentationFamilies.py after editor and local-reference verification.
namespace Tylevo.FieldAttachments.Core
{
    public static class GeneratedPresentationFamilies
    {
        public sealed class Entry
        {
            public readonly string Template, Controller, NativeClip, Bundle, Sha256, Family;
            public Entry(string template, string controller, string nativeClip, string bundle, string sha256, string family)
            { Template=template; Controller=controller; NativeClip=nativeClip; Bundle=bundle; Sha256=sha256; Family=family; }
        }
        private static readonly Entry[] Entries = {
            new Entry("5df8ce05b11454561e39243b", "weapon_kac_sr25_762x51", "sr25_look", "sr25_presentation", "1891AEDEBA70CC150A57CB751E59177C7C69CFE5645AC4F8EB9FF49156732341", "conventional-long-gun"),
            new Entry("5926bb2186f7744b1c6c6e60", "weapon_hk_mp5_navy3_9x19", "mp5_look", "mp5_presentation", "CE131E5E6AF215F5CC10703CF186FBC5E1938A769A4C680265E003E338402140", "compact-smg"),
            new Entry("5cadc190ae921500103bb3b6", "weapon_beretta_m9a3_9x19", "m9_look", "m9a3_presentation", "988D06C4EDD3B74AD8ECD132FEDB39C91284C033F3FF37B360D30700E42B6493", "pistol"),
        };
        public static Entry? For(string template)
        {
            foreach(var entry in Entries) if(entry.Template==template) return entry;
            return null;
        }
        public static bool IsAuthoredClip(string? name)
        {
            foreach(var entry in Entries) if(name=="Tylevo.FieldAttachments."+entry.Bundle) return true;
            return false;
        }
    }
}
